public class ChangeValue{
	public static void main(String[] args){
		/*int a=(int)33232.3232;
		long b=(long)121212.123;
		int c='a';
		double d=23242;
		System.out.println(a);
		System.out.println(b);
		System.out.println(c);
		System.out.println(d);*/
		// int a=100;
		// int b=100;
		// int c=a+b;
		// int d=a-b;
		// int e=a*b;
		// int f=a/b;
		// int g=a%b;
		// System.out.println(c);
		// System.out.println(d);
		// System.out.println(e);
		// System.out.println(f);
		// System.out.println(g);
		// int a=100;
		// int b=50;
		// a++;
		// System.out.println(a);
		// System.out.println(a++);
		// System.out.println(a);
		// ++a;
		// System.out.println(a);
		// System.out.println(++a);
		// System.out.println(a);
		// a--;
		// System.out.println(a);
		// System.out.println(a--);
		// System.out.println(a);
		// --a;
		// System.out.println(a);
		// System.out.println(--a);
		// System.out.println(a);
		//int c=--a+b++;//99+50=149;
		// System.out.println(c);
		// int a=20;
		// int b=19;
		// System.out.println(a>b);
		// System.out.println(a>=b);
		// System.out.println(a<b);
		// System.out.println(a<=b);
		// System.out.println(a==b);
		// System.out.println(a!=b);
		// int a=30;
		// int b=25;
		// boolean flag1=((a>b)&&(a<10))&&(b<30);
		// boolean flag2=((a>b)&&(a<10))||(b<30);
		// boolean flag3=!(a<b);
		// System.out.println(flag1);
		// System.out.println(flag2);
		// System.out.println(flag3);
		// String str=(a>=b?"a大于b":"a小于b");
		// System.out.println(str);
		 int a=3;
		 int b=4;
		// int c=(++a)*2-(a--)*3+(b++)-b--;
		// System.out.println(c);
		int temp1=((int)(a++)/2);
		int temp2=(b--);
		int temp3=(++a)*3;
		int temp4=(++b)*2;
		int temp5=(++a-b++);
		String flag=temp1+temp2+temp3>temp4-temp5?"OK":"NO";
		
		System.out.print("("+temp1+"+"+temp2+"+"+temp3+")"+">"+"("+temp4+"-"+temp5+")"+"所以输出"+flag);
		// System.out.println();
		// System.out.println(temp1);
		// System.out.println(temp2);
		// System.out.println(temp3);
		// System.out.println(temp4);
		// System.out.println(temp5);
	}
}